apiVersion: "stable.example.com/v1"
kind: TestRuleChecker
metadata:
  name: "test-rules"
  description: "my cluster, my rules"
  clusterName: "my cluster"
spec:
  rules:
    -  pods:
          $range: "all"
          namespace:
            $eq: "lirumlarum"
          spec:
            containers:
              $range: "all"
              image:
                $range:
                  $matches: "asadasd"
    # - cluster:
    #     min: 3
    #     max: 10
    # # - nodes:
    #     $range: "all"
    #     memory:
    #       min: 100GB
