apiVersion: "stable.example.com/v1"
kind: TestRuleChecker
metadata:
  name: "test-rules"
  description: "my cluster, my rules"
  clusterName: "my cluster"
spec:
  rules:
    -  pods:
        namespace: "kube-system"
        spec:
           containers:
             image:
               matches: "^(gcr.io/(google[-_]containers|k8s-minikube)|k8s.gcr.io)"
        status:
          phase: 
            equals: "Running"
    # - cluster:
    #     min: 3
    #     max: 10
    # # - nodes:
    #     $range: "all"
    #     memory:
    #       min: 100GB
