apiVersion: "stable.example.com/v1"
kind: TestRuleChecker
metadata:
  name: "test-rules"
  description: "my cluster, my rules"
  clusterName: "my cluster"
spec:
  rules:
  -  pods:
        namespace:
          $eq: "default"
        spec:
          containers:
            image:
              matches:
                $matches: "asadasd"
  - cluster:
      min: 3
      max: 10
  - nodes:
      memory:
        min: 100GB
