apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rulecheckers.stable.example.com
spec:
  scope: Cluster
  group: stable.example.com
  version: v1
  names:
    kind: RuleChecker
    plural: rulecheckers
    singular: rulechecker
    shortnames:
    - rchk
  validation:
    openAPIV3Schema:
          properties:
            spec:
              properties:
                rules:
                  type: array
                  items:
                    domain:
                      type: string
                    required:
                      - domain
                    pattern: "(Cluster|Node|Pod)"

