apiVersion: apps/v1
kind: Deployment
metadata:
  name: kelefstis
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kelefstis
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kelefstis
    spec:
      containers:
      - image: quay.io/endocode/k7s:latest
        name: kelefstis
        command: 
        - "/kelefstis"
        args: 
        - "-logtostderr"
        - "-v"
        - "8"
        - "2>&1" 
        volumeMounts:
          - name: kubeconfig
            mountPath: ".kube/"
            readOnly: true
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.5"
            memory: "100Mi"
      volumes:
      - name: kubeconfig
        secret:
          secretName: kelefstis
    