kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
rules:
- apiGroups: [""] 
  resources: ["nodes","pods", "rulecheckers"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["kelefstis.endocode.com"] 
  resources: ["rulecheckers"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] 
  resources: [ "pods/exec"]
  verbs: ["get", "watch", "list","create"] 
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
- kind: ServiceAccount
  name: kelefstis
  namespace: kube-system
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""