/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	samplecontrollerv1alpha1 "github.com/endocode/kelefstis/pkg/apis/samplecontroller/v1alpha1"
	versioned "github.com/endocode/kelefstis/pkg/client/clientset/versioned"
	internalinterfaces "github.com/endocode/kelefstis/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/endocode/kelefstis/pkg/client/listers/samplecontroller/v1alpha1"
)

// RuleCheckerInformer provides access to a shared informer and lister for
// RuleCheckers.
type RuleCheckerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RuleCheckerLister
}

type ruleCheckerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRuleCheckerInformer constructs a new informer for RuleChecker type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRuleCheckerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRuleCheckerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRuleCheckerInformer constructs a new informer for RuleChecker type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRuleCheckerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplecontrollerV1alpha1().RuleCheckers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplecontrollerV1alpha1().RuleCheckers(namespace).Watch(options)
			},
		},
		&samplecontrollerv1alpha1.RuleChecker{},
		resyncPeriod,
		indexers,
	)
}

func (f *ruleCheckerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRuleCheckerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ruleCheckerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&samplecontrollerv1alpha1.RuleChecker{}, f.defaultInformer)
}

func (f *ruleCheckerInformer) Lister() v1alpha1.RuleCheckerLister {
	return v1alpha1.NewRuleCheckerLister(f.Informer().GetIndexer())
}
