/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "github.com/endocode/kelefstis/pkg/apis/samplecontroller/v1alpha1"
	scheme "github.com/endocode/kelefstis/pkg/client/clientset/versioned/scheme"
)

// RuleCheckersGetter has a method to return a RuleCheckerInterface.
// A group's client should implement this interface.
type RuleCheckersGetter interface {
	RuleCheckers(namespace string) RuleCheckerInterface
}

// RuleCheckerInterface has methods to work with RuleChecker resources.
type RuleCheckerInterface interface {
	Create(*v1alpha1.RuleChecker) (*v1alpha1.RuleChecker, error)
	Update(*v1alpha1.RuleChecker) (*v1alpha1.RuleChecker, error)
	UpdateStatus(*v1alpha1.RuleChecker) (*v1alpha1.RuleChecker, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RuleChecker, error)
	List(opts v1.ListOptions) (*v1alpha1.RuleCheckerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RuleChecker, err error)
	RuleCheckerExpansion
}

// ruleCheckers implements RuleCheckerInterface
type ruleCheckers struct {
	client rest.Interface
	ns     string
}

// newRuleCheckers returns a RuleCheckers
func newRuleCheckers(c *SamplecontrollerV1alpha1Client, namespace string) *ruleCheckers {
	return &ruleCheckers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ruleChecker, and returns the corresponding ruleChecker object, and an error if there is any.
func (c *ruleCheckers) Get(name string, options v1.GetOptions) (result *v1alpha1.RuleChecker, err error) {
	result = &v1alpha1.RuleChecker{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rulecheckers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RuleCheckers that match those selectors.
func (c *ruleCheckers) List(opts v1.ListOptions) (result *v1alpha1.RuleCheckerList, err error) {
	result = &v1alpha1.RuleCheckerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rulecheckers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ruleCheckers.
func (c *ruleCheckers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rulecheckers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a ruleChecker and creates it.  Returns the server's representation of the ruleChecker, and an error, if there is any.
func (c *ruleCheckers) Create(ruleChecker *v1alpha1.RuleChecker) (result *v1alpha1.RuleChecker, err error) {
	result = &v1alpha1.RuleChecker{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rulecheckers").
		Body(ruleChecker).
		Do().
		Into(result)
	return
}

// Update takes the representation of a ruleChecker and updates it. Returns the server's representation of the ruleChecker, and an error, if there is any.
func (c *ruleCheckers) Update(ruleChecker *v1alpha1.RuleChecker) (result *v1alpha1.RuleChecker, err error) {
	result = &v1alpha1.RuleChecker{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rulecheckers").
		Name(ruleChecker.Name).
		Body(ruleChecker).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *ruleCheckers) UpdateStatus(ruleChecker *v1alpha1.RuleChecker) (result *v1alpha1.RuleChecker, err error) {
	result = &v1alpha1.RuleChecker{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rulecheckers").
		Name(ruleChecker.Name).
		SubResource("status").
		Body(ruleChecker).
		Do().
		Into(result)
	return
}

// Delete takes name of the ruleChecker and deletes it. Returns an error if one occurs.
func (c *ruleCheckers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rulecheckers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ruleCheckers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rulecheckers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched ruleChecker.
func (c *ruleCheckers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RuleChecker, err error) {
	result = &v1alpha1.RuleChecker{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rulecheckers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
