/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "github.com/endocode/kelefstis/pkg/apis/kelefstis/v1alpha1"
)

// FakeRuleCheckers implements RuleCheckerInterface
type FakeRuleCheckers struct {
	Fake *FakeSamplecontrollerV1alpha1
	ns   string
}

var rulecheckersResource = schema.GroupVersionResource{Group: "kelefstis.k8s.io", Version: "v1alpha1", Resource: "rulecheckers"}

var rulecheckersKind = schema.GroupVersionKind{Group: "kelefstis.k8s.io", Version: "v1alpha1", Kind: "RuleChecker"}

// Get takes name of the ruleChecker, and returns the corresponding ruleChecker object, and an error if there is any.
func (c *FakeRuleCheckers) Get(name string, options v1.GetOptions) (result *v1alpha1.RuleChecker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rulecheckersResource, c.ns, name), &v1alpha1.RuleChecker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuleChecker), err
}

// List takes label and field selectors, and returns the list of RuleCheckers that match those selectors.
func (c *FakeRuleCheckers) List(opts v1.ListOptions) (result *v1alpha1.RuleCheckerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rulecheckersResource, rulecheckersKind, c.ns, opts), &v1alpha1.RuleCheckerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RuleCheckerList{ListMeta: obj.(*v1alpha1.RuleCheckerList).ListMeta}
	for _, item := range obj.(*v1alpha1.RuleCheckerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ruleCheckers.
func (c *FakeRuleCheckers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rulecheckersResource, c.ns, opts))

}

// Create takes the representation of a ruleChecker and creates it.  Returns the server's representation of the ruleChecker, and an error, if there is any.
func (c *FakeRuleCheckers) Create(ruleChecker *v1alpha1.RuleChecker) (result *v1alpha1.RuleChecker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rulecheckersResource, c.ns, ruleChecker), &v1alpha1.RuleChecker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuleChecker), err
}

// Update takes the representation of a ruleChecker and updates it. Returns the server's representation of the ruleChecker, and an error, if there is any.
func (c *FakeRuleCheckers) Update(ruleChecker *v1alpha1.RuleChecker) (result *v1alpha1.RuleChecker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rulecheckersResource, c.ns, ruleChecker), &v1alpha1.RuleChecker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuleChecker), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRuleCheckers) UpdateStatus(ruleChecker *v1alpha1.RuleChecker) (*v1alpha1.RuleChecker, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rulecheckersResource, "status", c.ns, ruleChecker), &v1alpha1.RuleChecker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuleChecker), err
}

// Delete takes name of the ruleChecker and deletes it. Returns an error if one occurs.
func (c *FakeRuleCheckers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rulecheckersResource, c.ns, name), &v1alpha1.RuleChecker{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRuleCheckers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rulecheckersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RuleCheckerList{})
	return err
}

// Patch applies the patch and returns the patched ruleChecker.
func (c *FakeRuleCheckers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RuleChecker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rulecheckersResource, c.ns, name, data, subresources...), &v1alpha1.RuleChecker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuleChecker), err
}
